name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo greeting
        run: echo "hello world"
      - name: goodbye
        run: |
          echo "king"="king_of_db" >> $GITHUB_ENV
          echo "kind"="kind_of_db" >> $GITHUB_ENV
        shell: bash
      - name: get env
        shell: bash
        run: |
          arrayKing=( ${{ env.king }} ${{ env.kind }})
          for kin in "${arrayKing[@]}"
          do
            echo $kin
          done
